import { Users, ShieldCheck } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useAccess } from "@/features/access/AccessProvider";
import { fetchResponseTeamRoster, type ResponseTeamRoster } from "@/services/incidentOperations";
import { useEffect, useState } from "react";
const TEAM_LABELS: Record<string,string>={security:"Security",medical:"Medical",fire:"Fire & Rescue",search_rescue:"Search & Rescue",flood:"Flood & Disaster",humanitarian:"Humanitarian",volunteers:"Community Volunteers",response:"General Response"};
export function EmergencyTeamsPanel(){
 const {activeOrganization,hasPermission}=useAccess(); const [teams,setTeams]=useState<ResponseTeamRoster[]>([]); const [loading,setLoading]=useState(false);
 useEffect(()=>{if(!activeOrganization)return;setLoading(true);void fetchResponseTeamRoster(activeOrganization.id).then(setTeams).finally(()=>setLoading(false));},[activeOrganization]);
 if(!activeOrganization)return null;
 return <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ShieldCheck className="h-4 w-4"/>Emergency Response Teams</CardTitle><p className="text-xs text-muted-foreground">Organization-scoped teams available for incident assignment and dispatch.</p></CardHeader><CardContent>{loading?<p className="text-sm text-muted-foreground">Loading response teams…</p>:teams.length===0?<p className="text-sm text-muted-foreground">No emergency teams have been configured for this organization.</p>:<div className="grid gap-3 md:grid-cols-2">{teams.map(team=><div key={team.teamId} className="rounded-lg border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{team.teamName}</p><p className="text-xs text-muted-foreground">{TEAM_LABELS[team.teamType]??team.teamType}</p></div><span className="rounded-full border px-2 py-1 text-xs">{team.members.length} responder{team.members.length===1?"":"s"}</span></div><div className="mt-3 space-y-2">{team.members.length===0?<p className="text-xs text-amber-600 dark:text-amber-400">Unstaffed — dispatch will be rejected.</p>:team.members.map(member=><div key={member.membershipId} className="flex items-center gap-2 text-sm"><Users className="h-3.5 w-3.5 text-muted-foreground"/><span>{member.displayName}</span><span className="ml-auto text-xs text-muted-foreground">{member.status}</span></div>)}</div>{!hasPermission("incidents.assign")&&<p className="mt-3 text-[11px] text-muted-foreground">Team assignment is restricted to authorized coordinators.</p>}</div>)}</div>}</CardContent></Card>;
}
